export const palette = {
  brownBlack: "#190E05",
  darkBlue: "#28444C",
  mediumBrown: "#4E2510",
  mediumGreen: "#526D6A",
  darkTan: "#745F46",
  mediumBlue: "#748A9D",
  softGreen: "#78928D",
  warmGrey: "#8A8982",
  softBlue: "#9DA9AE",
  tan: "#A7967F",
};

export const theme = {
  pageBg: "#f6f3ee",
  surface: "#fffdf9",
  surfaceSolid: "#fffdf9",
  surfaceMuted: "#f7f3ec",
  controlSurface: "#f3ede4",
  text: palette.brownBlack,
  mutedText: palette.darkTan,
  border: "#ddd4c8",
  borderStrong: "#cbbfae",
  headerBorder: "#e4ddd3",
  shadowSm: "0 1px 0 rgba(25, 14, 5, 0.04)",
  shadowMd: "0 8px 24px rgba(25, 14, 5, 0.06)",
  link: palette.darkBlue,
  linkHover: palette.brownBlack,
  primary: palette.darkBlue,
  primaryHover: palette.brownBlack,
  primarySoftBg: "#e8efef",
  primarySoftBorder: "#c8d4d6",
  primarySoftText: palette.darkBlue,
  successBg: "#edf3f1",
  successBorder: "#c9d7d3",
  successText: palette.mediumGreen,
  warningBg: "#f6eee6",
  warningBorder: "#dcc8b3",
  warningText: palette.mediumBrown,
  neutralPillBg: "#f4efe8",
  neutralPillBorder: "#d6ccbf",
  neutralPillText: palette.darkTan,
};
